version: '3.8'
services:
  db:
    image: postgres:15
    container_name: fs-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fs-postgres-prod
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
