version: '3.8'
services:
  db:
    image: postgres:15                # Version de PostgreSQL
    container_name: fs-postgres-db # Nom du conteneur
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fs-postgres-prod
    ports:
      - "5432:5432"                  
    volumes:
      - ./db_data:/var/lib/postgresql/data